### ISSUE TITLE
Action fails when lint errors are found in unchanged files

### ISSUE THREAD

**Issue by yorkxin** [bufbuild/buf-lint-action#3]
Hi, I'm trying to use `buf lint` in an existing protobuf code base. There are files that does not pass the buf lint rules, in this case `buf-lint-action` itself fails because those files are not present in the pull request diff:

    Failed to write comments in-line: Unprocessable Entity: "Path is invalid and Pull request review thread review comments is invalid"

I think our use case is common for teams that has some protobuf files before introducing `buf` as their linter tool. Please consider supporting this use case.

As an alternative solution, this is what I chose to do:

1. Run `buf lint --error=format=json`
2. Use `jq` to format output in [this format](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message) so that GitHub Pull Request can show them under "Unchanged files with check annotations" section (in "Files changed" tab).

Also because the source code does not provide a FOSS license, I am not allowed to fix your program.

Thanks!

**Comment by amckinney** [comment]
Thanks for the issue! You're right, this is a common use case for anyone migrating to `buf`. I appreciate the recommendation for the format that renders the errors in the "Unchanged files with check annotations" section, too. In this case, we shouldn't need to use `jq` though - we can just rely on the functions we already have available in Typescript (similar to what we do for in [fileAnnotationToComment](https://github.com/bufbuild/buf-lint-action/blob/ab87fc59e13ee43fb4fcfe67444c8a9339eb0d0a/src/github.ts#L86)).

In the meantime, the action _should_ show you the errors you care about in the console alongside the error you shared above. This is handled [here](https://github.com/bufbuild/buf-lint-action/blob/ab87fc59e13ee43fb4fcfe67444c8a9339eb0d0a/src/run.ts#L139) so that we continue to surface lint warnings in the presence of errors just like this. Was the `buf lint` output available for you there?

As for the license, the license we use in our private repositories was accidentally used. We'll get this updated to the same license in the [buf](https://github.com/bufbuild/buf/blob/master/LICENSE) repository right away. We welcome contributions if you're still interested in lending a hand! Otherwise, we'll track this and get a fix out for it soon.

**Comment by yorkxin** [comment]
@amckinney Thank you so much for your quick response and changes to the license :)

I did saw `buf lint` outputs in GitHub Actions, so that part is working as expected.

For now I think we'll use our own solutions for now, to print `::error` messages in the step, because the configuration is simpler; we don't have to pass GitHub token in order to run `buf` checkers.

We also have a minimal config for `buf breaking` instead of using `buf-breaking-action`: checking out the base branch in another folder (add another step of `actions/checkout`), and run `buf breaking` in the head checkout, to compare the code in the other folder. This way we can avoid considering how `buf` interacts with the git repository internally.

Looking forward to see the improvements of your GitHub Actions :)

**Comment by doriable** [comment]
We have now updated this Github Action to use the file annotations, so updating to our new release will remove the requirement for the `github.token` to be set in the configurations: https://github.com/bufbuild/buf-lint-action/releases/tag/v0.3.0

Thank you for filing this and using our Github Actions and feel free to re-open if there are any concerns with the release! :)

**Comment by yorkxin** [comment]
@doriable Thanks. The new version works perfect with our project!
